import type { TerminalTheme } from '@/types/theme'

// All themes sorted A-Z
const themeDefinitions: TerminalTheme[] = [
  {
    id: 'andromeeda',
    name: 'Andromeeda',
    type: 'dark',
    shikiTheme: 'andromeeda',
    colors: {
      background: '#23262E',
      foreground: '#D5CED9',
      selection: '#3E4451',
      cursor: '#D5CED9',
      titleBar: '#1E2127',
      black: '#1E2127',
      red: '#F92672',
      green: '#A6E22E',
      yellow: '#E6DB74',
      blue: '#66D9EF',
      magenta: '#AE81FF',
      cyan: '#00E8C6',
      white: '#D5CED9',
      brightBlack: '#5C6370',
      brightRed: '#FF669D',
      brightGreen: '#BEED5F',
      brightYellow: '#F3EA98',
      brightBlue: '#8DE8F7',
      brightMagenta: '#C9A4FF',
      brightCyan: '#5FF3D6',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    type: 'dark',
    shikiTheme: 'ayu-dark',
    colors: {
      background: '#0B0E14',
      foreground: '#BFBDB6',
      selection: '#273747',
      cursor: '#E6B450',
      titleBar: '#0D1017',
      black: '#0D1017',
      red: '#F07178',
      green: '#AAD94C',
      yellow: '#FFB454',
      blue: '#39BAE6',
      magenta: '#D2A6FF',
      cyan: '#95E6CB',
      white: '#BFBDB6',
      brightBlack: '#565B66',
      brightRed: '#FF8F9A',
      brightGreen: '#C5E478',
      brightYellow: '#FFCB7F',
      brightBlue: '#6DD1F5',
      brightMagenta: '#E4C5FF',
      brightCyan: '#B5F4E3',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    type: 'dark',
    shikiTheme: 'catppuccin-mocha',
    colors: {
      background: '#1E1E2E',
      foreground: '#CDD6F4',
      selection: '#45475A',
      cursor: '#F5E0DC',
      titleBar: '#181825',
      black: '#45475A',
      red: '#F38BA8',
      green: '#A6E3A1',
      yellow: '#F9E2AF',
      blue: '#89B4FA',
      magenta: '#F5C2E7',
      cyan: '#94E2D5',
      white: '#BAC2DE',
      brightBlack: '#585B70',
      brightRed: '#F38BA8',
      brightGreen: '#A6E3A1',
      brightYellow: '#F9E2AF',
      brightBlue: '#89B4FA',
      brightMagenta: '#F5C2E7',
      brightCyan: '#94E2D5',
      brightWhite: '#A6ADC8',
    },
  },
  {
    id: 'dark-plus',
    name: 'Dark+',
    type: 'dark',
    shikiTheme: 'dark-plus',
    colors: {
      background: '#1E1E1E',
      foreground: '#D4D4D4',
      selection: '#264F78',
      cursor: '#D4D4D4',
      titleBar: '#323233',
      black: '#1E1E1E',
      red: '#F44747',
      green: '#6A9955',
      yellow: '#DCDCAA',
      blue: '#569CD6',
      magenta: '#C586C0',
      cyan: '#4EC9B0',
      white: '#D4D4D4',
      brightBlack: '#808080',
      brightRed: '#F44747',
      brightGreen: '#6A9955',
      brightYellow: '#DCDCAA',
      brightBlue: '#569CD6',
      brightMagenta: '#C586C0',
      brightCyan: '#4EC9B0',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    shikiTheme: 'dracula',
    colors: {
      background: '#282A36',
      foreground: '#F8F8F2',
      selection: '#44475A',
      cursor: '#F8F8F2',
      titleBar: '#21222C',
      black: '#21222C',
      red: '#FF5555',
      green: '#50FA7B',
      yellow: '#F1FA8C',
      blue: '#BD93F9',
      magenta: '#FF79C6',
      cyan: '#8BE9FD',
      white: '#F8F8F2',
      brightBlack: '#6272A4',
      brightRed: '#FF6E6E',
      brightGreen: '#69FF94',
      brightYellow: '#FFFFA5',
      brightBlue: '#D6ACFF',
      brightMagenta: '#FF92DF',
      brightCyan: '#A4FFFF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'dracula-soft',
    name: 'Dracula Soft',
    type: 'dark',
    shikiTheme: 'dracula-soft',
    colors: {
      background: '#282A36',
      foreground: '#F8F8F2',
      selection: '#44475A',
      cursor: '#F8F8F2',
      titleBar: '#21222C',
      black: '#21222C',
      red: '#FF9580',
      green: '#8AFF80',
      yellow: '#FFFF80',
      blue: '#9580FF',
      magenta: '#FF80BF',
      cyan: '#80FFEA',
      white: '#F8F8F2',
      brightBlack: '#6272A4',
      brightRed: '#FFAA99',
      brightGreen: '#A2FF99',
      brightYellow: '#FFFF99',
      brightBlue: '#AA99FF',
      brightMagenta: '#FF99CC',
      brightCyan: '#99FFEE',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'everforest-dark',
    name: 'Everforest Dark',
    type: 'dark',
    shikiTheme: 'everforest-dark',
    colors: {
      background: '#2D353B',
      foreground: '#D3C6AA',
      selection: '#543A48',
      cursor: '#D3C6AA',
      titleBar: '#272E33',
      black: '#4B565C',
      red: '#E67E80',
      green: '#A7C080',
      yellow: '#DBBC7F',
      blue: '#7FBBB3',
      magenta: '#D699B6',
      cyan: '#83C092',
      white: '#D3C6AA',
      brightBlack: '#5C6A72',
      brightRed: '#F85552',
      brightGreen: '#8DA101',
      brightYellow: '#DFA000',
      brightBlue: '#3A94C5',
      brightMagenta: '#DF69BA',
      brightCyan: '#35A77C',
      brightWhite: '#DFDDC8',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    shikiTheme: 'github-dark',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      selection: '#3B5070',
      cursor: '#C9D1D9',
      titleBar: '#161B22',
      black: '#484F58',
      red: '#FF7B72',
      green: '#3FB950',
      yellow: '#D29922',
      blue: '#58A6FF',
      magenta: '#BC8CFF',
      cyan: '#39C5CF',
      white: '#B1BAC4',
      brightBlack: '#6E7681',
      brightRed: '#FFA198',
      brightGreen: '#56D364',
      brightYellow: '#E3B341',
      brightBlue: '#79C0FF',
      brightMagenta: '#D2A8FF',
      brightCyan: '#56D4DD',
      brightWhite: '#F0F6FC',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    type: 'light',
    shikiTheme: 'github-light',
    colors: {
      background: '#FFFFFF',
      foreground: '#24292F',
      selection: '#C8E1FF',
      cursor: '#24292F',
      titleBar: '#F6F8FA',
      black: '#24292F',
      red: '#CF222E',
      green: '#116329',
      yellow: '#4D2D00',
      blue: '#0550AE',
      magenta: '#8250DF',
      cyan: '#1B7C83',
      white: '#6E7781',
      brightBlack: '#57606A',
      brightRed: '#A40E26',
      brightGreen: '#1A7F37',
      brightYellow: '#633C01',
      brightBlue: '#0969DA',
      brightMagenta: '#6639BA',
      brightCyan: '#3192AA',
      brightWhite: '#8C959F',
    },
  },
  {
    id: 'houston',
    name: 'Houston',
    type: 'dark',
    shikiTheme: 'houston',
    colors: {
      background: '#17191E',
      foreground: '#E0E0E0',
      selection: '#2E3440',
      cursor: '#E0E0E0',
      titleBar: '#0F1115',
      black: '#0F1115',
      red: '#FF6B6B',
      green: '#5DE4C7',
      yellow: '#FFFAC2',
      blue: '#89DDFF',
      magenta: '#FAE4FC',
      cyan: '#5DE4C7',
      white: '#E0E0E0',
      brightBlack: '#4E5579',
      brightRed: '#FF8E8E',
      brightGreen: '#91F1D4',
      brightYellow: '#FFFDD5',
      brightBlue: '#B4EAFF',
      brightMagenta: '#FCF0FD',
      brightCyan: '#91F1D4',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'material-theme-ocean',
    name: 'Material Ocean',
    type: 'dark',
    shikiTheme: 'material-theme-ocean',
    colors: {
      background: '#0F111A',
      foreground: '#8F93A2',
      selection: '#1F2233',
      cursor: '#FFCC00',
      titleBar: '#090B10',
      black: '#090B10',
      red: '#F07178',
      green: '#C3E88D',
      yellow: '#FFCB6B',
      blue: '#82AAFF',
      magenta: '#C792EA',
      cyan: '#89DDFF',
      white: '#EEFFFF',
      brightBlack: '#464B5D',
      brightRed: '#FF8B92',
      brightGreen: '#DDFFA7',
      brightYellow: '#FFE585',
      brightBlue: '#9CC4FF',
      brightMagenta: '#E1ACFF',
      brightCyan: '#A3F7FF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'min-dark',
    name: 'Min Dark',
    type: 'dark',
    shikiTheme: 'min-dark',
    colors: {
      background: '#1F1F1F',
      foreground: '#B392F0',
      selection: '#2D2D2D',
      cursor: '#B392F0',
      titleBar: '#171717',
      black: '#1F1F1F',
      red: '#F97583',
      green: '#85E89D',
      yellow: '#FFAB70',
      blue: '#79B8FF',
      magenta: '#B392F0',
      cyan: '#9ECBFF',
      white: '#F6F8FA',
      brightBlack: '#6A737D',
      brightRed: '#FDAEB7',
      brightGreen: '#BAF7C7',
      brightYellow: '#FFD5A8',
      brightBlue: '#AFDBFF',
      brightMagenta: '#D4C4FB',
      brightCyan: '#CAE5FF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    type: 'dark',
    shikiTheme: 'monokai',
    colors: {
      background: '#272822',
      foreground: '#F8F8F2',
      selection: '#49483E',
      cursor: '#F8F8F2',
      titleBar: '#1E1F1C',
      black: '#272822',
      red: '#F92672',
      green: '#A6E22E',
      yellow: '#F4BF75',
      blue: '#66D9EF',
      magenta: '#AE81FF',
      cyan: '#A1EFE4',
      white: '#F8F8F2',
      brightBlack: '#75715E',
      brightRed: '#F92672',
      brightGreen: '#A6E22E',
      brightYellow: '#F4BF75',
      brightBlue: '#66D9EF',
      brightMagenta: '#AE81FF',
      brightCyan: '#A1EFE4',
      brightWhite: '#F9F8F5',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    type: 'dark',
    shikiTheme: 'night-owl',
    colors: {
      background: '#011627',
      foreground: '#D6DEEB',
      selection: '#1D3B53',
      cursor: '#80A4C2',
      titleBar: '#011221',
      black: '#011627',
      red: '#EF5350',
      green: '#22DA6E',
      yellow: '#ADDB67',
      blue: '#82AAFF',
      magenta: '#C792EA',
      cyan: '#21C7A8',
      white: '#FFFFFF',
      brightBlack: '#575656',
      brightRed: '#EF5350',
      brightGreen: '#22DA6E',
      brightYellow: '#FFEB95',
      brightBlue: '#82AAFF',
      brightMagenta: '#C792EA',
      brightCyan: '#7FDBCA',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    shikiTheme: 'nord',
    colors: {
      background: '#2E3440',
      foreground: '#D8DEE9',
      selection: '#434C5E',
      cursor: '#D8DEE9',
      titleBar: '#242933',
      black: '#3B4252',
      red: '#BF616A',
      green: '#A3BE8C',
      yellow: '#EBCB8B',
      blue: '#81A1C1',
      magenta: '#B48EAD',
      cyan: '#88C0D0',
      white: '#E5E9F0',
      brightBlack: '#4C566A',
      brightRed: '#BF616A',
      brightGreen: '#A3BE8C',
      brightYellow: '#EBCB8B',
      brightBlue: '#81A1C1',
      brightMagenta: '#B48EAD',
      brightCyan: '#8FBCBB',
      brightWhite: '#ECEFF4',
    },
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    type: 'dark',
    shikiTheme: 'one-dark-pro',
    colors: {
      background: '#282C34',
      foreground: '#ABB2BF',
      selection: '#3E4451',
      cursor: '#528BFF',
      titleBar: '#21252B',
      black: '#282C34',
      red: '#E06C75',
      green: '#98C379',
      yellow: '#E5C07B',
      blue: '#61AFEF',
      magenta: '#C678DD',
      cyan: '#56B6C2',
      white: '#ABB2BF',
      brightBlack: '#5C6370',
      brightRed: '#E06C75',
      brightGreen: '#98C379',
      brightYellow: '#E5C07B',
      brightBlue: '#61AFEF',
      brightMagenta: '#C678DD',
      brightCyan: '#56B6C2',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    type: 'dark',
    shikiTheme: 'rose-pine',
    colors: {
      background: '#191724',
      foreground: '#E0DEF4',
      selection: '#2A273F',
      cursor: '#524F67',
      titleBar: '#1F1D2E',
      black: '#26233A',
      red: '#EB6F92',
      green: '#9CCFD8',
      yellow: '#F6C177',
      blue: '#31748F',
      magenta: '#C4A7E7',
      cyan: '#EBBCBA',
      white: '#E0DEF4',
      brightBlack: '#6E6A86',
      brightRed: '#EB6F92',
      brightGreen: '#9CCFD8',
      brightYellow: '#F6C177',
      brightBlue: '#31748F',
      brightMagenta: '#C4A7E7',
      brightCyan: '#EBBCBA',
      brightWhite: '#E0DEF4',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    shikiTheme: 'solarized-dark',
    colors: {
      background: '#002B36',
      foreground: '#839496',
      selection: '#073642',
      cursor: '#839496',
      titleBar: '#00252E',
      black: '#073642',
      red: '#DC322F',
      green: '#859900',
      yellow: '#B58900',
      blue: '#268BD2',
      magenta: '#D33682',
      cyan: '#2AA198',
      white: '#EEE8D5',
      brightBlack: '#002B36',
      brightRed: '#CB4B16',
      brightGreen: '#586E75',
      brightYellow: '#657B83',
      brightBlue: '#839496',
      brightMagenta: '#6C71C4',
      brightCyan: '#93A1A1',
      brightWhite: '#FDF6E3',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    type: 'dark',
    shikiTheme: 'tokyo-night',
    colors: {
      background: '#1A1B26',
      foreground: '#A9B1D6',
      selection: '#33467C',
      cursor: '#C0CAF5',
      titleBar: '#16161E',
      black: '#15161E',
      red: '#F7768E',
      green: '#9ECE6A',
      yellow: '#E0AF68',
      blue: '#7AA2F7',
      magenta: '#BB9AF7',
      cyan: '#7DCFFF',
      white: '#A9B1D6',
      brightBlack: '#414868',
      brightRed: '#F7768E',
      brightGreen: '#9ECE6A',
      brightYellow: '#E0AF68',
      brightBlue: '#7AA2F7',
      brightMagenta: '#BB9AF7',
      brightCyan: '#7DCFFF',
      brightWhite: '#C0CAF5',
    },
  },
  {
    id: 'vitesse-dark',
    name: 'Vitesse Dark',
    type: 'dark',
    shikiTheme: 'vitesse-dark',
    colors: {
      background: '#121212',
      foreground: '#DBD7CA',
      selection: '#353535',
      cursor: '#DBD7CA',
      titleBar: '#0A0A0A',
      black: '#121212',
      red: '#D1426F',
      green: '#4D9375',
      yellow: '#D4976C',
      blue: '#6394BF',
      magenta: '#CB7676',
      cyan: '#5EAAB5',
      white: '#DBD7CA',
      brightBlack: '#5D5D5F',
      brightRed: '#E55381',
      brightGreen: '#5FAE8B',
      brightYellow: '#E8B080',
      brightBlue: '#7CAED3',
      brightMagenta: '#DF8A8A',
      brightCyan: '#72BEC9',
      brightWhite: '#F2F0E5',
    },
  },
]

// Create themes record from definitions
export const themes: Record<string, TerminalTheme> = Object.fromEntries(
  themeDefinitions.map((theme) => [theme.id, theme])
)

// Export as sorted list for UI dropdowns
export const themeList = themeDefinitions

// Get theme by ID with fallback
export function getTheme(id: string): TerminalTheme {
  return themes[id] || themes['dracula']
}
